### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBoT#48] opened 2018-01-11 00:16 UTC
Use Google Style Docstrings for documentation. 
Style Guide: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by KingAkeem** [comment] 2018-01-11 00:17
I'm currently working on this right now.

**Comment by PSNAppz** [comment] 2018-01-11 07:16
@KingAkeem Close this when the issue is fixed.

**Closed** 2018-01-11 17:51 UTC
Labels: documentation
